[main]
# Muestra el reloj
time-format=%l:%M %p
# Estilo personalizado
style=/home/mario/.config/gtklock/style.css
# Ocultar el cursor tras unos segundos de inactividad
time-timeout=1
# Desactivar el aviso de Caps Lock
show-caps-lock=false
# Fondo
background=/home/mario/Downloads/forest.png
