# ~/.config/foot/foot.ini
font=JetBrainsMonoNL Nerd Font:size=11

[colors-dark]
alpha=1.0

# Fondo negro puro y texto blanco nítido
background=000000
foreground=ffffff

# Selección de texto
selection-background=444444
selection-foreground=ffffff

# Colores Normales (Paleta TTY / Kitty Clásica)
regular0=000000 # Negro
regular1=c00000 # Rojo
regular2=00a800 # Verde
regular3=a8a800 # Amarillo
regular4=0000a8 # Azul
regular5=a800a8 # Magenta
regular6=00a8a8 # Cyan
regular7=c0c0c0 # Blanco

# Colores Brillantes (Alta saturación)
bright0=555555 # Gris brillante
bright1=ff5555 # Rojo brillante
bright2=55ff55 # Verde brillante
bright3=ffff55 # Amarillo brillante
bright4=5555ff # Azul brillante
bright5=ff55ff # Magenta brillante
bright6=55ffff # Cyan brillante
bright7=ffffff # Blanco puro

#include=/usr/share/foot/themes/vga
