[flavor]
use = "dracula.yazi"

[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" }
]
extract = [
	{ run = 'ouch decompress "$1"', desc = "Extract here", for = "unix" }
]
image = [
	{ run = 'imv "$@"', orphan = true, desc = "Open Image" }
]
pdf = [
	{ run = 'zathura "$@"', orphan = true, desc = "Open PDF" }
]

[open]
rules = [
	{ name = "*.webp", use = "image" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "play" },
	{ mime = "audio/*", use = "play" },
	{ name = "*.7z", use = "extract" },
	{ mime = "application/zip", use = "extract" },
	{ mime = "application/x-tar", use = "extract" },
	{ mime = "application/x-bzip2", use = "extract" },
	{ mime = "application/x-7z-compressed", use = "extract" },
	{ mime = "application/x-rar", use = "extract" },
	{ mime = "application/pdf", use = "pdf" }
]

[mgr]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
